project:
  type: website

website:
  title: "Baseball"
  navbar:
    left:
      - href: home-runs.qmd
        text: "Home runs"
      - href: sluggers.qmd
        text: "Sluggers"

execute:
  echo: false

format:
  html:
    theme: cosmo